Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,6 +5,9 @@ on:
     branches:
       - main
   pull_request:
+    types:
+      - opened
+      - synchronize
     branches:
       - main
 
@@ -29,5 +32,16 @@ jobs:
     - name: Build project
       run: xcodebuild clean build -workspace CleverTapSDK.xcworkspace -scheme CleverTapSDK
 
-    - name: Run tests
-      run: xcodebuild test -workspace CleverTapSDK.xcworkspace -scheme CleverTapSDKTests -destination 'platform=iOS Simulator,name=iPhone 14'
+#     - name: Run tests
+#       run: xcodebuild test -workspace CleverTapSDK.xcworkspace -scheme CleverTapSDKTests -destination 'platform=iOS Simulator,name=iPhone 14'
+    
+    - name: Validate PR Title
+        run:|
+          PR_TITLE=$(git log --format=%s -1 ${{ github.event.pull_request.head.sha }})
+          if [[ ! $PR_TITLE =~ ^SDK-[0-9]+ ]]; then
+            echo "Invalid PR title format. Please use 'SDK-{number}' format."
+            exit 1
+          fi
+
+
+
