Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,12 +37,15 @@ jobs:
 #       run: xcodebuild test -workspace CleverTapSDK.xcworkspace -scheme CleverTapSDKTests -destination 'platform=iOS Simulator,name=iPhone 14'
     
     - name: Validate PR Title
-      run: |
-          PR_TITLE=$(git log --format=%s -1 ${{ github.event.pull_request.head.sha }})
-          if [[ ! $PR_TITLE =~ ^SDK-[0-9]+ ]]; then
-            echo "Invalid PR title format. Please use 'SDK-{number}' format."
-            exit 1
-          fi
-
+#       run: |
+#           PR_TITLE=$(git log --format=%s -1 ${{ github.event.pull_request.head.sha }})
+#           if [[ ! $PR_TITLE =~ ^SDK-[0-9]+ ]]; then
+#             echo "Invalid PR title format. Please use 'SDK-{number}' format."
+#             exit 1
+#           fi
+      uses: dylanvann/check-pull-request-title@v1
+      with:
+          # Match pull request titles in the form UI-1234 - Message.
+          pattern: '^SDK-\d* - '
 
 
